Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 4
  end

  nodes = {
    "manager01" => "192.168.56.10",
    "worker01" => "192.168.56.11",
    "worker02" => "192.168.56.12"
  }

  nodes.each do |name, ip|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: ip
      node.vm.synced_folder "./scripts", "/home/vagrant/services/scripts"
      node.vm.synced_folder "./monitoring", "/home/vagrant/services/monitoring"
      node.vm.synced_folder "./services/.swarm", "/home/vagrant/services/.swarm", create: true
      node.vm.synced_folder "./services/database", "/home/vagrant/services/database"
      node.vm.synced_folder "./services/nginx", "/home/vagrant/services/nginx"
      node.vm.synced_folder "./services/portainer", "/home/vagrant/services/portainer"

      node.vm.provision "shell", path: "scripts/install-docker.sh", privileged: true

      if name == "manager01"
        node.vm.provision "shell", path: "scripts/manager-init.sh", args: [ip], privileged: true
      else
        node.vm.provision "shell", path: "scripts/worker-join.sh", privileged: true
      end

      node.vm.provider "virtualbox" do |vb|
        vb.name = "do9-#{name}"
      end
    end
  end
end